services:
  crewai:
    container_name: seo_strategist_ai
    build: .
    tty: true
    stdin_open: true
    env_file:
      - .env
    environment:
      - SERPER_API_KEY=${SERPER_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
