fetch_all_posts_task:
  description: >
    Fetch all blog posts.
    Save these posts to a CSV file.
  expected_output: >
    A string with the path of the CSV file containing the content of the posts.
  agent: content_downloader
  tools:
    - fetch_posts

identify_posts_cannibalization_task:
  description: >
    Read the CSV file containing blog posts and identify duplicates and similar posts.
    Your final report should list all duplicate and similar posts with their IDs.

  # Also flag links that are not identical, but that could also be cannibalizing.
  # For example:
  #   example 1: https://rafaelcarvalho.tv/area-de-pessoas-1/ and https://rafaelcarvalho.tv/area-de-mães/
  #   example 2: https://rafaelcarvalho.tv/afiliado/ and https://rafaelcarvalho.tv/afiliados/
  expected_output: >
    A report listing duplicate and similar posts with their IDs.
  # A list of flagged lines with potential content cannibalization.
  # The list must be delivered by grouping the posts that were identified similar content as follows:

  # Cannibalization 01:
  # - post ID: title, link
  # - post ID: title, link

  # Cannibalization 02:
  # - post ID: title, link
  # - post ID: title, link
  agent: content_analyst
  tools:
    - read_csv
    - find_duplicates_and_similarities
  inputs:
    filepath: tmp/blog_posts.csv
  outputs:
    data: $read_csv.data
  steps:
    - tool: read_csv
      args:
        file_path: $inputs.file_path
    - tool: find_duplicates_and_similarities
      args:
        data: $steps[0].output


# recommend_post_actions_task:
#   description: >
#     For each set of duplicate posts, recommend which ones to keep, delete, or merge.
#   expected_output: >
#     Actionable recommendations for each set of duplicate posts.
#   agent: content_analyzer

# suggest_new_keywords_task:
#   description: >
#     Analyze current keyword coverage and suggest new posts to cover important keywords not currently addressed.
#   expected_output: >
#     A list of new post topics with suggested keywords.
#   agent: seo_strategist

# merge_content_task:
#   description: >
#     Provide specific recommendations on how to merge duplicate posts into a single optimized post.
#   expected_output: >
#     Detailed merging guidelines for each set of duplicate posts.
#   agent: content_merger
