content_downloader:
  role: >
    Content Downloader
  goal: >
    Retrieve all posts from a blog and save them at a CSV file.
  backstory: >
    You are skilled at access and download content from Wordpess blogs.
  llm: gemma2
  memory: True
  tools:
    - fetch_posts

content_analyst:
  role: >
    Content Analyst
  goal: >
    Identify duplicate and similar blog posts from a CSV file.
  backstory: >
    As a content analyst, you excel in identifying patterns and 
    similarities in large datasets, ensuring content uniqueness.
  llm: gemma2
  memory: True
  tools:
    - read_csv
    - find_duplicates_and_similarities
#     - read_posts_file_tool
#     - keyword_analyzer
#     - content_quality_analyzer

# seo_strategist:
#   role: >
#     SEO Strategist
#   goal: >
#     Enhance keyword coverage by identifying important keywords not currently covered and suggesting new posts.
#   backstory: >
#     Expert in SEO strategies, you can identify gaps in keyword coverage and recommend topics to address these gaps.
#   tools:
#     - seo_keyword_suggestion

# content_merger:
#   role: >
#     Content Merger
#   goal: >
#     Provide detailed recommendations on how to merge duplicate posts.
#   backstory: >
#     Experienced in content creation and editing, you ensure that merged content is coherent and optimized.
#   tools:
#     - content_merger
